name: CI

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      
 
      
      # Instalar as dependências NPM/Yarn
      - name: Install dependencies 
        run: cd backend && yarn 
        

          
      # Executar a build   
      - name: Run build
        run: cd backend && yarn build
          
      # Copiar pasta dist para dentro da Digital Ocean
      - name: copy dist to Digital Ocean
        uses: cd backend && appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key:  ${{ secrets.SSH_KEY }}
          source: "dist"
          target: "test"
        
      # Substituir o código existente na pasta "dist" pelo novo código
      # Executar "yarn" na Digital Ocean        
      # Executar as migrations do TypeORM
      # Restart no servidor Node.js
